export const SET_FORM_PRISTINE = 'SET_FORM_PRISTINE';
export const SET_FIELDS = 'SET_FIELDS';
export const SET_FIELDS_ERRORS_TO_DISPLAY = 'SET_FIELDS_ERRORS_TO_DISPLAY';
export const SET_HAS_FORM_ERRORS_TO_DISPLAY = 'SET_HAS_FORM_ERRORS_TO_DISPLAY';
export const SET_FORM_ERRORS = 'SET_FORM_ERRORS';
export const SET_DISABLE_STATUS = 'SET_DISABLE_STATUS';
